#pragma once

#include "egsspch.h"
#include "Egss/Core.h"
#include "Egss/Renderer/Mesh.h"
#include "Egss/Voxel/VoxelField3D.h"

#include <glm/glm.hpp>

namespace Egss {

	// Stitches a coarse chunk's boundary layer to a neighbour meshed at half
	// (or a quarter) its stride, watertightly rather than approximately.
	//
	// Two earlier attempts at this (see the changelog, 2026-08-16) fanned a
	// coarse cell's subdivided seam face from the cell's centre and were
	// reverted: the fan's *side* faces, perpendicular to the seam, were left
	// as flat coarse triangles, so two neighbouring cells disagreed about how
	// many vertices sat on the edge between them -- a T-junction, invisible to
	// the eye and fatal to the watertightness check (every edge used by
	// exactly two triangles).
	//
	// The fix here marks *edges*, not faces, and every consumer of a marked
	// edge fetches its subdivision from one function keyed on the edge's own
	// endpoints (`SubdivideEdge`), so two tetrahedra that share a physical
	// edge -- whether they are two of one cube's six tets or two tets either
	// side of a cube or chunk boundary -- always agree, by construction, with
	// nothing to coordinate.
	//
	// Built entirely on `MarchingTetrahedra`: every tetrahedron this produces,
	// however it was arrived at, is hard-classified into exactly one of three
	// kinds against the cube's fixed six-tet decomposition and its one
	// boundary face, and each kind reduces to one or more calls to the
	// existing, unmodified `MarchingTetrahedra::Cell` -- no new
	// triangle-emission code, no lookup table.
	//
	//   - Two "cap" tets have a whole face on the boundary. That face is
	//     recursively quadrisected down to the fine chunk's own lattice
	//     spacing, sampling the true field fresh at every new point (the
	//     field is exact at any integer lattice point regardless of a
	//     chunk's stride -- "coarse" and "fine" differ only in which points a
	//     mesher samples), then every small triangle is coned to the tet's
	//     one apex corner (the one not on the boundary) and meshed as an
	//     ordinary small tetrahedron.
	//   - Two "collar" tets touch the boundary along exactly one edge. That
	//     edge is subdivided the same way, and the tet is split into a strip
	//     of small tetrahedra sharing its two off-edge corners.
	//   - Two tets meet the boundary at a single corner only and are meshed
	//     exactly as `MarchingTetrahedra::Cell` already does.
	//
	// **Out of scope, deliberately:** a cell that would need this treatment
	// on two faces at once -- a chunk corner or edge where two different
	// stride transitions meet. `Cell` falls back to plain, unsubdivided
	// tetrahedra there (matching an ordinary interior cell), which trades
	// today's full 2D seam for a much smaller 1D seam-of-seams. See the plan
	// this was built from for why that residual is being accepted rather than
	// solved in the same pass.
	class EGSS_API VoxelTransition
	{
	public:
		// A lattice point sampled fresh from the field: its integer
		// coordinate, world position, and signed distance.
		struct LatticePoint
		{
			glm::ivec3 Lattice;
			glm::vec3 Position;
			float Value;
		};

		// Which of a cube cell's six faces border a chunk meshed at a finer
		// stride. Matches no particular axis convention beyond being
		// consistent with itself -- callers only ever need to name one face.
		enum Face { PosX = 0, NegX = 1, PosY = 2, NegY = 3, PosZ = 4, NegZ = 5 };

		// The `2^depth + 1` lattice points subdividing the straight lattice
		// segment from `a` to `b` into equal steps. `b - a` must divide
		// evenly by `2^depth` on every axis it differs on -- true whenever
		// `depth` came from `log2(coarseStride / fineStride)`, since a chunk
		// boundary's stride ratio is always a power of two.
		//
		// Every point is a fresh `field.DistanceAt` sample, never a linear
		// interpolation of the endpoints. Two callers subdividing the same
		// physical edge -- in either direction, see the note on ordering in
		// the .cpp -- land on the same lattice positions and read the same
		// values, because there is only one field to read.
		static void SubdivideEdge(const VoxelField3D& field,
			const glm::ivec3& a, const glm::ivec3& b, int depth,
			std::vector<LatticePoint>& out, const glm::ivec3* about = nullptr);

		// The barycentric lattice points of triangle `a, b, c`, where `b` and
		// `c` are each `2^depth` fine steps from `a` along the triangle's two
		// edges from `a`. Flat array of `(n+1)(n+2)/2` points for `n = 2^depth`,
		// indexed by `FaceIndex(u, v, n)`.
		//
		// The three boundary rows (`v = 0`, `u = 0`, and the hypotenuse
		// `u + v = n`) are each generated by a call to `SubdivideEdge`, not by
		// this function's own interior arithmetic -- so a boundary edge
		// shared with a neighbouring tet's own `SubdivideEdge` call is
		// guaranteed bit-identical, rather than merely arithmetically
		// equivalent to it.
		static void SubdivideFace(const VoxelField3D& field,
			const glm::ivec3& a, const glm::ivec3& b, const glm::ivec3& c,
			int depth, std::vector<LatticePoint>& out,
			const glm::ivec3* about = nullptr);

		// Index into `SubdivideFace`'s output for grid coordinate `(u, v)`,
		// `n = 2^depth`. Row `v` starts after `v * (n + 1) - v * (v - 1) / 2`
		// points from the shorter rows before it.
		static int FaceIndex(int u, int v, int n)
		{
			return v * (n + 1) - (v * (v - 1)) / 2 + u;
		}

		// One coarse cube cell at lattice `origin`, `stride` voxels per side.
		// `boundaryMask` names which single face (see `Face`) borders a
		// neighbour at `stride / ratio`; `ratio` is 2 or 4. Appends to `data`.
		//
		// If `boundaryMask` has zero or more than one bit set, meshes all six
		// tets plainly instead -- see the class comment's "out of scope" note.
		static void Cell(const VoxelField3D& field, const glm::ivec3& origin,
			int stride, unsigned int boundaryMask, int ratio, MeshData& data,
			const glm::ivec3* about = nullptr);

		// A rectangular range of cells, stepping by `stride`, all sharing the
		// one boundary face named in `boundaryMask`.
		// `about` is the lattice point emitted positions are measured from,
		// and must match whatever the interior of the same chunk was meshed
		// with -- the boundary layer's triangles share vertices with it.
		static void MeshBoundaryLayer(const VoxelField3D& field,
			const glm::ivec3& min, const glm::ivec3& max,
			int stride, unsigned int boundaryMask, int ratio, MeshData& data,
			const glm::ivec3* about = nullptr);
	};

}
